ReplicaSet is new version of ReplicationController. the main differnce between both is selector in ReplicaSet(spec section), which is to take care for other pods with same selectors attributes.
selector:
  matchLabels:
	tier: app
  
-----------------------------------------------------------

kubectl replace -f replicaset-defination.yaml

kubectl scale --replias=6 replicaset myapp-replicaset


------------------------------------------------------

if in the question it is asked to delete pods related to replicaset so that replicaset can create new pods with changed defination, then instead of deleting each pod seperately use below
kubectl scale --replias=0 replicaset myapp-replicaset
and then scale back to required.
kubectl scale --replias=4 replicaset myapp-replicaset
------------------------------------------------------

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
