apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: replicaset-1
spec:
   replicas: 2
   selector:
      matchLabels:
        tier: nginx
   template:
     metadata:
       labels:
        tier: nginx
     spec:
       containers:
       - name: nginx
         image: nginx

------------------------

 kubectl get pods --selector env=dev
 
 
 Identify the POD which is part of the prod environment, the finance BU and of frontend tier?
 kubectl get pod --selector env=prod,bu=finance,tier=frontend
