

update image for existing deployment
kubectl set image deployment/myapp-dep nginx=nginx:1.9.1

kubectl rollout status deployment/myapp-dep

kubectl rollout history deployment/myapp-dep

kubectl rollout undo deployment/myapp-deployment

kubectl rollout history deployment nginx --revision=1

kubectl rollout undo deployment nginx --to-revision=1

kubectl describe deployments. nginx | grep -i image:

kubectl edit deployment frontend


apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      name: webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - image: kodekloud/webapp-color:v2
        name: simple-webapp
        ports:
        - containerPort: 8080
          protocol: TCP




------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:

    matchLabels:
      app: nginx
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.0

        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1



--------------------------------------

- Creating a deployment, checking the rollout status and history
kubectl create deployment nginx --image=nginx:1.16
kubectl rollout history deployment nginx

- Using the --revision flag
kubectl rollout history deployment nginx --revision=1
kubectl rollout history deployment nginx --revision=3

Using the --record flag
kubectl set image deployment nginx nginx=nginx:1.17 --record
kubectl rollout history deployment nginx

Undo a change
kubectl edit deployments.apps nginx --record=true
kubectl set image deployment nginx nginx=nginx:1.17 --record=true

To rollback to specific revision we will use the --to-revision flag
kubectl rollout undo deployment nginx --to-revision=1
kubectl rollout history deployment nginx
