
apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-container
    image: my-image
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 3


----------------

readinessProbe:
      tcpSocket:
        port: 3306


-------------

readinessProbe:
   exec:
     command: 
       - cat
       - /app/is_ready
