apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: redis
    image: redis
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: green


------------------

env:
  - name: APP_COLOR
    valueFrom:
        configMapRef:
        or
        secretKeyRef:
