apiVersion: v1 
kind: Secret 
metadata:
  name: webapp-config-map
data:
  DB_Host: mysql
  DB_User: root
  DB_Password: pwd
  
------------
--commands:
kubectl create secret <config-name> --from-literal=<key>=<value>
kubectl create secret app-secret 
    --from-literal=DB_Host=mysql 
    --from-literal=DB_User=root
    --from-literal=DB_Password=pwd
kubectl create secret app-secret --from-file-app_secret.properties
------------

--complete ref to configMap

apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-color
  name: webapp-color
spec:
  containers:
  - envFrom:
    - configMapRef: 
        name: webapp-config-map
    image: kodekloud/webapp-color
    name: webapp-color
    
    
    
--single env to configMap

apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-color
  name: webapp-color
spec:
  containers:
  - env:
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef: 
             name: webapp-config-map
             key: APP_COLOR
    image: kodekloud/webapp-color
    name: webapp-color
