
docker run --user=1001 ubuntu sleep 3600

docker run --cap-add MAC_ADMIN ubuntu


Settings over the Pod level, will implement on all containers inside the Pod 
but settings over the Container are related only to particular Container.


-----
At Pod Level

apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "3600"]
      
--------
At container Level

apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1000
      
------------

Note: Capabilities are only supported at the cotnainer level and not at the POD level

apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 1000
      capabilities:
        add: ["MAC_ADMIN"]


-------------------

Que: What is the user used to execute the sleep process within the ubuntu-sleeper pod?
And: kubectl exec ubuntu-sleeper -- whoami
