
user account are for humans
serviceaccount is for machines. Jenkins, promethus, other apps use service account.
--------------------------------


kubectl create serviceaccount my-service-account
----------

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: assembly-prod
spec:
  serviceAccountName: my-service-account
  containers:
    - name: my-container
      image: my-image
      command: ["sleep", "3600"]



---------------


kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: assembly-prod
  name: testreadrole
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
    
    
---------------



kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testrolebinding
  namespace: assembly-prod
subjects:
  - kind: ServiceAccount
    name: my-service-account
    namespace: assembly-prod
roleRef:
  kind: Role
  name: testreadrole
  apiGroup: rbac.authorization.k8s.io
  
-----------------------


to check the ls or print the file which is mounted within pod for serviceaccount:
kubectl exec web-app -- ls /var/run/secrets/kubernetes.io/serviceaccount

kubectl cat web-app -- ls /var/run/secrets/kubernetes.io/serviceaccount/token

---------------------

kubectl auth can-i create pods --as=system:serviceaccount:<namespace>:<serviceaccountname>

kubectl create serviceaccount deploy

kubectl create role deployrole --verb=create,get,list --resources

kubectl create rolebinding deploybind --role=deployrole --serviceaccount=default:deploy

kubectl auth can-i create pods --as=system:serviceaccount:default:deploy


apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: deploy
  containers:
    - name: my-container
      image: my-image
      command: ["sleep", "3600"]
