
kubectl taint nodes <node-name> key=value:<taint-effect>

taint-effect: NoSchedule | PreferNoSchedule | NoExecute
NoSchedule—The pod will not get scheduled to the node without a matching toleration.
NoExecute—This will immediately evict all the pods without the matching toleration from the node.
PerferNoSchedule—This is a softer version of NoSchedule where the controller will not try to schedule a pod with the tainted node. However, it is not a strict requirement.


kubectl describe node kubemaster | grep Taint


-----------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: bee
spec:
  containers:
    - name: bee
      image: nginx
  tolerations:
  - key: spray
    value: moretein
    operator: Equals
    effect: NoSchedule


---------------------------

Que: Remove the taint on controlplane, which currently has the taint effect of NoSchedule.
Ans: kubectl taint nodes controlplane node-role.kubernetes.io/control-plane:NoSchedule-
