kubectl label nodes <node-name> <label-key>=<label-name>


kubectl label nodes node-1 size=large


-----------------------------

apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: data-processor
      image: data-processor
nodeSelector:
  size: Large
